### ISSUE TITLE
Set perspective for cube to take all available screen

### ISSUE THREAD

**Issue by kasp9** [giawa/opengl4tutorials#11]
I'm taking a look at [tutorial 15](https://github.com/giawa/opengl4tutorials/tree/master/OpenGLTutorial15/OpenGLTutorial15). I'm wondering how I could set the default camera zoom (or perspective) for the cube to take all avaiable screen space (without overflow).

I'm aiming to achieve something like this:
![image](https://github.com/giawa/opengl4tutorials/assets/155548968/c8c379e1-6c02-4d1c-82e2-2d61fafe7693)

In provided code, I would have to press "W" until the zoom makes the cube take all available screen height.  Is it a way to set this default zoom dinamically taking into account the cube size so it always take all screen height or width without overflowing?

**Comment by giawa** [comment]
Hey there,

Yup, this is possible!  There's a bit of math involved though.  This reminds me of the 'picking' problem, where you have to try to work out what objects might be under your mouse by mapping your mouse co-ordinates into 3d space.  We're going to be going from "screen-space" co-ordinates and converting them to world space, but solving for something a bit different this time.

We need to translate the top of the window from screen space into world space.  We can do that by creating a `Vector4` for the top of the window (in OpenGL screen space co-ordinates the top of the window has a Y of 1).  We then translate this by the inverse of the projection matrix to get us a decent chunk of the way into world space.

This gives us the position of something in world space that is right at the front of the projection matrix, at the very top of the window.  Now, we need to extend along the edge of the perspective matrix until we hit the top of the cube (which is at Y=1 as defined by the vertices of our cube).  Our existing position already has some Y value, so we subtract it from 1 to figure out how far we need to travel along the edge of the perspective.

We know the angle of the line we are following, since that's the field of view, which is a value we passed into `CreatePerspectiveFieldOfView`.  So now we know the total Y to travel, and the angle, so we can find the Z, which should give us the distance the camera needs to be away for the cube to fit (almost).

```
// build inverse projection matrix to use for our ray cast
var inverseProjection = Matrix4.CreatePerspectiveFieldOfView(0.6f, (float)width / height, 0.1f, 1000f).Inverse();

// build ray that goes through the top of the screen towards the cube
var rayOrigin = new Vector4(0, 1, 0, 1) * inverseProjection;
rayOrigin /= rayOrigin.W;

// find the Y edge of the triangle we are solving for
var yDiff = 1 - rayOrigin.Y;
// find the Z edge of the triangle we are solving for
var distance = yDiff / Math.Tan(0.5f * 0.6f);
```

Remember the cube also is 1 unit closer to the camera (the vertices have Z values of +1 and -1), so we need to account for that.  We also need to account for the 0.1f zNear when computing the perspective matrix (this is actually part of our rayOrigin).

```
distance -= rayOrigin.Z;    // to account for zNear in the perspective matrix calculation
distance += 1;              // to account for the cube having +1 and -1 Z values for vertices
```

Then we can plug this into our creation of the `Camera` to set the camera at this starting position.

```
camera = new Camera(new Vector3(0, 0, distance), Quaternion.Identity);
```

Which should get you something like this:

![image](https://github.com/giawa/opengl4tutorials/assets/3923687/36bc4c9e-43df-4f5a-83b4-d96245df05b0)

Note:  In many cases when working out screen space to world space you need to also include the model and view matrices.  In this case, there is no model matrix (the cube is at position `0, 0, 0`), and the view matrix hasn't been computed yet (it is the camera, which is what we are trying to solve for).  So we only needed the projection matrix.

Good luck!

- Giawa
