### ISSUE TITLE
Not splitting correctly

### ISSUE THREAD

**Issue by mitkonikov** [giawa/opengl4tutorials#4]
In tutorial 16 > class ObjLoader > Line 307, 308, 309, I get weird splitting.
The string to split is 3/5/5 (for example) > After splitting is 3/5, and could not calculate int.Parse(indices[0]) - vertexOffset.
I was wondering, was that working for you? Because I exported an objs from 3ds max. There were some problems like additional spaces in the obj (where should not excisted), but this issue is in the code. And I was wondering is Tutorial 16 still in construction or is it complete? I am on vacation now, but when I get home, I will try the objs from the link you gave to the previous issue. Thanks.

**Comment by mitkonikov** [comment]
With the obj from the web-site you gave, I put it on my dropbox : subwoofer_obj: https://www.dropbox.com/s/29fpn1q1qhdfssk/subwoofer_obj.obj?dl=0 , and subwoofer_mtl: https://www.dropbox.com/s/m24ozch47zcpydb/subwoofer_obj.mtl?dl=0 . These files are from the official website. When I put them and run the program, I get a new error : Tutorial 16 > objLoader.cs > Line 323 : when tries to see whats inside unpackedUvs[triangle[0]] , triangle[0] is -128. So wtf? It says Out of Range ex. ? Why triangle[0] is negative 128 ?

**Comment by giawa** [comment]
Hi mitkonikov,

The object file reader doesn't support the full .obj specification.  It was just meant to demo loading a file in, so some exporters use interesting formatting/etc that are not currently supported.  I've checked out your file and it looks like some groups relied on vertex data from previous groups, and sometimes new vertex data is just injected into the model at any point in the file.  I had never seen this before in any of my sample files.

I've updated the tutorial to include some code to deal with your particular type of file.  I hope this will help with you being able to load your .obj files.  However, for a full library you may need to look to a loader that supports the entire .obj specification.  Alternatively you can also fork this code and make modifications.  If you add any functionality please feel free to issue a pull request so that I can merge it back into the main branch.

Please let me know if the new code works for you.  Thanks!

Giawa

**Comment by mitkonikov** [comment]
It works, nice, thanks. But what I noticed, is that when loading obj with one material, you need to add a new line to the end of the obj.mtl with just newmtl. I think I can fix it, just I will fork it, and than you check the result. I will fork it now and fix it, you decide. I found one more bug, and I fixed it, so now I am going to fork it and put the code. Its very simple.

**Comment by mitkonikov** [comment]
Test out the new changes with your obj samples.

**Comment by giawa** [comment]
Awesome, I'll check it out and likely merge later today.  Thanks for the contribution!
